### ISSUE TITLE
Переименуйте в libilya

### ISSUE THREAD

**Issue by ovivvvu** [DragonFire1230/libilya#1]
×n(i$·Ú!ò&TÞ„€‘D£Ï\cú¯ûÍh6Gðê¯:Î
ÿsÎñqƒIüÓËéÝÀ]xŒÖæh1êA[.ìX®ð£oÙih>Ñ´&SÒ˜g“|^TZ4Ê™ýúOŒ—FN^¾Å½WènMm€(Î>ìóG?‚ÉVŠ¨Ç˜ãüW¦Ñõ-6'�T½;H¼Ü º”wšŠfßòÏßAüYÂƒUV˜˜ïûÙùH7P¿ŠÓ§ÁƒfÝœòOjD=Ã¾Š:‡¿F¡!Zˆ+ÖaTëŒqÚãnpoRþþÆqVë•'¬cáIöf³!fÅ ‡þ£yRgrÛBÏX·-:Í¨Q@Š—93UÓqAòÉáCoi-¼¶�Ïb¿"¹ÚevQ“óß+Äµßl¼ë¬Tƒ5›÷ý‘ÐòpØÚÙ™Sˆ‘‰ÖÎ>_¾
t—
|¾2µ£‘j–9Hú�èÕù2ææ$á!2q3}ÇŸ·ˆ8ê�‹†z¡F&ªé{jvuºùå¯ x¥ÓÚŒF0æ5qšL²ß†›¦xÞ|+Û}Ò¥¹#‡UŸlÅ³¼Ä¨K‰9½¿Üjx.|Õ;˜À&²¿éè•ß˜SªÊ-G4»yI?X’(M(Oùp^<ñ{ÖV?1G½xfÖ#ö»ò=¡åˆ:ÐÞaà&O‘Ÿ.P}ÕXÏz6Ë§ü>B×
«$½±ˆJÙïÇ€±uN3¨Wø$åTÊûo’œœÃXÓxYmð¹L´¦#ëX…:£ÛšJU«Üº“œo§iee<dAÂU¨Äðo    åWŒk¶Z´Œ]K_îÉÇ0¶DåŠJ÷Ee!es…¹éäâÑËTíë ôïÁ7óæEè‡'^êÚÂŸ½ÀÁxÇònÎâÜý^×A2Éërü &Nv'ê•Å
4kÛ‘“Uý&T§˜8i:ÂàN:½ÍYrD·ÑôBl#À²ð(A'=ì†ÓÅšC¦nfwhêM8Q=rPuå)¼º.%ûgÚâqðöTu9zåußZ®¼R¡AF²ÊvE|¶P{Ó±S‰XøðWÉ{êï7½£-ð¢ò¢
øp¾Ê¸…ß0CÍð¿EËµ¸‰µ4…Úa‹TíTf§Ýê·}s‹¨s
Ž#ê¦ðY³mï*õú”²åŠñ4­ýýƒþK±ß7Ê¶îƒ¯âSªÙNdüþQI­~ô¾àÓz®#ê 4-2ðÁ%³QÒªEÍÓ$ô„Ó£Ž½†&#øcÕ
‹™¹Ol÷µÕä¼’Ñª®U„º#È+ŒÌÕæ¯Q?~£sš£Î”¬|%ž_IÏXzÊ¾:¼Ž”<Ž+
õl%ºÆZ&¾;~¹ÓodDžIžË®Éè=õOœÌ¼Õþ„Âa¼¯ÊÍ!ÿŒ«g?ÎîåXnÞúÝk¶5èñÌ‰dbuRºçJRwÐŠÂŽ?´eLGÕåä‡<¾óò
S³ãÆ’(àäØ­üü49.Aþw³oc
)qI‹»
D¨Î?®«¿‚5…uüÕ«æ¾fèÚ½[Þï:•x»u.ž4/ø™í…JØÕ)lÝhxœsÁ7·GÂáÑ§ç_q¼ÊÆ¾¼°WOÜÖj|kûçµ£¯-wpÿ$ÖŒgD'¼›z0o±[¥ò$XP¸î§íe¾4À%K™ŒÇ†l™…
JìÃæÆi7%(LÏŠCå€Š‘”˜Æl†€Áie£r‡†<˜‰ýE#c(¸‡¼¹|ÆÐWÅêH1‘aÄJþ“(^NG1­jþŒ
óáÕáìïÿtJG™w+Ç¯ú¨IfQ½ßœ1~›;7
ü4j°vw¸½½ùwà›¢:© ¢
Ùv[\#@îëïI‹¡›ö^Øý¤XŽ7m®¹6=þãj�nÈ°F)ØÙNÅwLQ‰l³¡ÓBÂ";ÆÏá    Xêq½�ZÕ—'mý¡3Äq§p¢¼tÑˆg(Äå’ð®˜Gø]§škÛ´,,rÄ4$qÁâ€I‹B%BkB,Xm#x6/+Š­u+DDÊÙþF=ƒ"7¿|3âqE$±{—8Ó®AwYúªeS#F
²²3¼ÄR'8<Vf5"A‡)’÷«²VñÌŠ­    ˆv#&P{¦NJ§Aƒž%D6ÂL‚,¢®g]Õ}X¢7jù
0 >j"‡¼)å¯™õÀO+ZíI¡<KÏÙa?†ÒŸa¦‘R®†#ƒ¨eOÖpÝŸ„Ò³oqg"roòª>a¼n    UÈÕaä°`¢6¤ùø¥|á:z@6õ?~

**Comment by ItsHoul** [comment]
согл

**Comment by DragonFire1230** [comment]
Готово
